### ISSUE TITLE
Couldn't open the line: line with format PCM_SIGNED 44100.0 Hz ...

### ISSUE THREAD

**Issue by markstock** [ddf/Minim#45]
Loading stereo .wav files (mono seem to load fine) using...

```
crowd3[isize] = minim.loadFile(sketchPath(newfilename));
```

...I get the following two errors for each file:

```
==== JavaSound Minim Error ====
==== Couldn't open the line: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.

==== JavaSound Minim Error ====
==== Unable to return a SourceDataLine: unsupported format - PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian
```

It seems that this has been a problem in the past, and some folks had solved it:
https://importgeek.wordpress.com/tag/couldnt-open-the-line-line-with-format-pcm_signed-44100-0-hz/
http://forum.processing.org/one/topic/why-can-t-i-play-more-than-one-audiosample.html
https://github.com/processing/processing/issues/1677

But these solutions involve copying `libpulse-java.so` and `pulse-java.jar` from openjdk into the processing/java directory. I have `jre1.8.0_60-1.8.0_60-fcs.x86_64` installed and it contains no pulse-java.jar file at all.

I am on Fedora 21, Processing 3.0b5, Minim 2.2.1.

**Comment by markstock** [comment]
I should add that these files and this setup seems to work fine on OSX 10.10.x.

**Comment by ddf** [comment]
To be clear: is it that any stereo file fails to load or that if you try to load more than one stereo fail some of them fail?

I don't have a Fedora install to test with, unfortunately, but I can try to repro this in Ubuntu.

**Comment by markstock** [comment]
I'm loading about 100 files: some stereo, some mono, but I don't yet know if all of them throw the error---it'd take a bit of commenting to test that. Is there an issue with loading multiple files into separate AudioPlayer objects? I made a small test program that loads three of the same sound files, and it works fine.

**Comment by markstock** [comment]
OK, it throws two sets for each mono file (64 throw for 32 mono files), and 71 errors over 67 stereo sound files. I can't associate the errors with files, obviously.

**Comment by ddf** [comment]
Good to know. Your test case loads all files in setup, correct? 

It's probably just a resource availability issue in the Linux JavaSound implementation. AudioPlayer is not a super good option when dealing with a very large number of files. Each AudioPlayer requests an output resource (SourceDataLine) and is continually pushing data to it in its own Thread. I'm not so sure that's intended usage for that JavaSound resource. It's my plan to rewrite how AudioPlayer works so that this does not happen, but in the meantime you could request one AudioOutput from Minim, and then load all of your audio files into FilePlayer objects. You'd then patch the FilePlayers to the output before playing them and unpatch them when they are finished playing.

**Comment by markstock** [comment]
I can't seem to find documentation for FilePlayer objects. How many FilePlayer objects can be playing simultaneously?

**Comment by ddf** [comment]
FilePlayer docs are here:
http://code.compartmental.net/minim/fileplayer_class_fileplayer.html

How many can play simultaneously depends on how fast your system is. There
is no limit to how many can be patched to an AudioOutput, but eventually so
many will be generating at once that you will probably start to hear
crackles from buffer underrun.

**Comment by ddf** [comment]
Ok, I was just able to repro this in Ubuntu 14.04 using Processing 3.0b5. All I had to do was load the same file a bunch of times. If I load it 16 times, everything is fine. It's the 17th time and up that the error occurs. What seems strange is that I still get an AudioPlayer back and I can play it. No sound comes out, but I am seeing a waveform drawn as if the file is being played in fast-forward, which makes me think that I'm getting a working output from JavaSound that is just connected to nothing...

**Comment by ddf** [comment]
There appears to be a limit of 16 open SourceDataLines for the same audio format in both the version of Java included with Processing (an Oracle Java 8, I think) as well as OpenJDK 7. The default Java installation seems to not have Pulse included.

For now, I've fixed it so that loadFile will return null if the underlying system is not able to open a SourceDataLine to play the file: https://github.com/ddf/Minim/commit/3fe9e45e5843aeeecf8f9c9335a406a81d03961d

**Comment by senisioi** [comment]
A workaround would be to use an array of AudioSamples and make sure you don't load them twice (via loadSample). Once the samples are loaded, you can call trigger() on them individually.

**Comment by infovore** [comment]
> A workaround would be to use an array of AudioSamples and make sure you don't load them twice (via loadSample). Once the samples are loaded, you can call trigger() on them individually.

you say that, @senisioi, but I'm still getting an identical error: Processing 3.02 on Raspbian Jessie. (Yes, I'm trying to run this under new Processing 3 on ARM).

With WAV, MP3 or AIFF, I get told at point of trying to load a sample that 

    ==== Couldn't open the line: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.

and 

    ==== JavaSound Minim Error ====
    ==== Couldn't acquire an output.

Any thoughts? It feels like it's the same issue, and this is now six months old.

**Comment by ddf** [comment]
The "Couldn't acquire an output" error is really just a repeat of the "Couldn't open the line" error that comes before it. In the first error the "line" is a JavaSound DataLine and the error indicates that JavaSound's audio system could not create one to perform audio output with the given properties (it tries to create an output for each AudioSample). 

A thing you could try is attempting to create an AudioOuput with getLineOut and see what kinds of outputs are actually supported on Raspbian Jesse. You could then create Sampler UGens (http://code.compartmental.net/minim/sampler_class_sampler.html) and patch() them to the output.

Apologies for the complete lack of updates in the last six months, my video game work is keeping me quite busy and I haven't had the time to work on Minim lately. :(

**Comment by infovore** [comment]
OK, thanks, Damien. Looks like I’ve got some more poking to do. At least
Minim loads on the Pi, which is more than the official Sound library does
(thanks to its _demand_ for 64-bit). I’ll update this thread with how I get
on.

t.

**Comment by infovore** [comment]
@ddf OK, so I just made a dumb-as-a-sack-of-hammers demo consisting of acquiring an AudioOutput, setting up a Sampler, and triggering it. And it seemed to work fine. So I'm going to port all the many samples to be many samplers in my application, and we'll see how we go from there. Will continue to keep posting updates.

**Comment by ddf** [comment]
Great, good to hear that works at least.

**Comment by infovore** [comment]
@ddf 1.5 steps forward, 1 step back.

So: I've ported my code to use `Sample`, got that running on my OSX device. I then moved it over to the Raspberry Pi and lo and behold, it works! This is good. However, it only works through the on-board audio out (which is garbage PWM). I've got a USB audio interface that I've been using instead of that, which sounds much better - but which I'm now trying to specify inside the Processing code.

So I took a squint at the [code sample here](https://forum.processing.org/two/discussion/3109/how-to-get-multiple-audio-outputs-with-minim) on how to use multiple outputs, took my chance with making a new `Mixer`... and we're back to `Couldn't open the line: Line unsupported` .

I'm not particularly familiar with JavaSound. It feels like what I need to be doing is specifying the output _and_ the correct format to open that Line with? I've tried listing all the available mixers with `getMixerInfo`, but have not been able to list any available Lines on any of them - even the ones that have been working!

So there's a small amount of forward progress, but I'm now bashing my head into JavaSound. Any thoughts?

**Comment by ddf** [comment]
If you use setOutputMixer on your Minim object to change the output mixer to one from the sound card (see: https://github.com/ddf/Minim/blob/master/examples/Advanced/setOutputMixer/setOutputMixer.pde), then hopefully getLineOut with no arguments will actually return an output that connects your card. One tricky thing is that sometimes it's not clear from the mixer name whether it even supports an output line or not. You can query a Mixer to see what it supports with isLineSupported, see: https://docs.oracle.com/javase/tutorial/sound/accessing.html

**Comment by cheungbe** [comment]
I'm having the same problem on a Raspberry Pi but with using getLineIn()

Couldn't open the line: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.

Any thoughts on how to resolve?

**Comment by Brumelove** [comment]
I am facing the same issue, nothing seems to make it work
==== Don't know the ID3 code TSSE

==== JavaSound Minim Error ====
==== Couldn't open the line: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.

=== Minim Error ===
=== Couldn't load the file assets/audio/1.mp3

**Comment by I-blueHand-I** [comment]
Hey I got same error
I went on many forums to find an issue but it still doesn't work.
I am on a Raspi 4 8Go Ram and the new 64Bit Rasbian OS. I tried with the 32B sis but doesn't work too. 

I've made a videoGame with processing and I exported it. When I run the program it gives me this error. 

==== Don't know the ID3 code TSSE

==== JavaSound Minim Error ====
==== Couldn't open the line: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.

If someone has an solution, I'll appreciate ! 
thanks

**Comment by ddf** [comment]
Since I don't have a Raspberry Pi to test with, I can't really verify this issue or replicate it. The best I can suggest is providing different arguments to `getLineOut` to try to figure out what format is actually available on the system and setting different output mixers as I suggest above. The ID3 code error is not fatal and won't prevent decoding of an mp3 and the "Couldn't open the line" error comes after Minim attempts to open a `Line` object from JavaSound. Since everything depends on what comes back from JavaSound, it might be the case that there is some configuration of JavaSound that needs to happen before it will work, which I am not familiar enough with these days to provide direction for.

**Comment by I-blueHand-I** [comment]
Hey thanks for your reply. 
I tried with xubuntu on rip 4 and it seems to work fine. 

thank you
